server:
  port: 8087


eureka:
  client:
    service-url:
      defaultzone: http://eureka1:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}

spring:
  application:
    name: provider

