server:
  port: 8080
spring:
  application:
    name: order-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      rate: 10
      probability: 1

eureka:
  client:
    service-url:
      defaultzone: http://eureka1:8761/eureka