server:
  port: 8012

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      enabled: true  #\u5F00\u542F\u7F51\u5173\uFF0C\u9ED8\u8BA4\u662F\u5F00\u542F\u7684
      routes: #\u8BBE\u7F6E\u8DEF\u7531\uFF0C\u6CE8\u610F\u662F\u6570\u7EC4\uFF0C\u53EF\u4EE5\u8BBE\u7F6E\u591A\u4E2A\uFF0C\u6309\u7167 id \u505A\u9694\u79BB
        - id: user-service-router  #\u8DEF\u7531 id\uFF0C\u6CA1\u6709\u8981\u6C42\uFF0C\u4FDD\u6301\u552F\u4E00\u5373\u53EF
          uri: http://localhost:8013  #\u8BBE\u7F6E\u771F\u6B63\u7684\u670D\u52A1 ip:port
          predicates:
            - Path=/user/**  #\u548C\u670D\u52A1\u4E2D\u7684\u8DEF\u5F84\u5339\u914D,\u662F\u6B63\u5219\u5339\u914D\u7684\u6A21\u5F0F
        - id: order-service-router
          uri: http://localhost:8014
          predicates:
            - Path=/order/**
eureka:
  client:
    service-url:
      defaultzone: http://eureka1:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
