server:
  port: 8081
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        rate: 10
        probability: 1



eureka:
  client:
    service-url:
      defaultzone: http://eureka1:8761/eureka


#需要手动 开启断路器的使用
feign:
  circuitbreaker:
    enabled: true

