server:
  port: 8071
spring:
  application:
    name: zuul-service

eureka:
  client:
    service-url:
      defaultzone: http://eureka1:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}

zuul:
  routes:
    payment:
      path: /payment/**   #\u6240\u6709\u5339\u914D /payment/**\u7684\u8BF7\u6C42\u90FD\u4F1A\u8F6C\u53D1\u5230payment-service\u8FD9\u4E2A\u670D\u52A1\u53BB\u6267\u884C
      serviceId: payment-service #\u670D\u52A1\u540D\u79F0