server:
  port: 8081

spring:
  application:
    name: eureka_client

eureka:
  client:
    service-url: #eureka 服务端和客户端的交互地址,集群用,隔开
      defaultZone: http://eureka2:8761/eureka,http://eureka3:8761/eureka,http://eureka:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  server:

    eviction-interval-timer-in-ms: 30000 #清除无效节点的频率(毫秒)--定期删除
    enable-self-preservation: true #server 的自我保护机制，
    renewal-percent-threshold: 0.85 #85%，如果在一个机房的 client 端，15 分钟内有 85%的 client 没有续约，那么则可能是网络原因，认为服务实例没有问题，不会剔除他们，宁可放过一万，不可错杀一个，确保高可用

  instance:
      hostname: localhost # 服务主机名称
      instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port} # 实例 id
      prefer-ip-address: true # 服务列表以 ip 的形式展示
      lease-renewal-interval-in-seconds: 10 # 表示 eureka client 发送心跳给 server 端的频率
      lease-expiration-duration-in-seconds: 20 #表示 eureka server 至上一次收到 client 的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该实例




